# This workflow will install Python dependencies, (IN FUTURE) run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Build Matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  python_build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        version: ["3.12.1", "3.11.7", "3.10.11", "3.9.13"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install Pip Dependencies
      run: python -m pip install --upgrade pip
    - name: Install AppOpener
      run: python -m pip install AppOpener
    - name: Install Shiv
      run: python -m pip install --upgrade shiv
    - name: Build/Export
      run: |
        shiv -e main:main -o AutomatedAppOpener.pyzw -r <(echo AppOpener)
    - uses: actions/upload-artifact@v4
      with:
        name: AutomatedAppOpener ${{ matrix.os }} For Python v${{ matrix.version }}
        path: |
          ${{github.workspace}}/AutomatedAppOpener.pyzw
        if-no-files-found: warn
